# Generated by Django 5.2.11 on 2026-05-12
import re

from django.db import migrations, models


_INVALID_USERNAME_CHARS = re.compile(r"[^a-z0-9_]+")
_MULTIPLE_UNDERSCORES = re.compile(r"_+")


def _normalize_username(username: str) -> str:
    value = (username or "").strip().lower()
    value = _INVALID_USERNAME_CHARS.sub("_", value)
    value = _MULTIPLE_UNDERSCORES.sub("_", value).strip("_")
    return value or "user"


def _next_unique_username(existing: set[str], seed: str, max_length: int = 150) -> str:
    base = _normalize_username(seed)[:max_length] or "user"
    candidate = base
    suffix = 1
    while candidate.lower() in existing:
        suffix_value = f"_{suffix}"
        candidate = f"{base[: max_length - len(suffix_value)]}{suffix_value}"
        suffix += 1
    return candidate


def populate_usernames(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    users = list(User.objects.using(db_alias).all().order_by("id"))

    reserved_usernames: set[str] = set()
    for user in users:
        if not user.username:
            continue
        normalized = _normalize_username(user.username)
        candidate = _next_unique_username(reserved_usernames, normalized)
        if user.username != candidate:
            user.username = candidate
            user.save(update_fields=["username", "updated_at"])
        reserved_usernames.add(candidate.lower())

    for user in users:
        if user.username:
            continue
        local_part = (user.email or "").split("@", 1)[0] or "user"
        candidate = _next_unique_username(reserved_usernames, local_part)
        user.username = candidate
        user.save(update_fields=["username", "updated_at"])
        reserved_usernames.add(candidate.lower())


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
    ]
